# Generated by Django 6.0.6 on 2026-06-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_imagemetadata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemetadata',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
