# Generated by Codex on 2026-06-11

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageAsset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("object_key", models.CharField(max_length=512, unique=True)),
                ("thumbnail_key", models.CharField(blank=True, max_length=512)),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        default="private",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upload_requested", "Upload requested"),
                            ("uploaded", "Uploaded"),
                            ("embedding_pending", "Embedding pending"),
                            ("indexed", "Indexed"),
                            ("failed", "Failed"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="upload_requested",
                        max_length=32,
                    ),
                ),
                ("embedding_model", models.CharField(blank=True, max_length=128)),
                ("embedding_version", models.CharField(blank=True, max_length=128)),
                ("embedding_dimensions", models.PositiveIntegerField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["owner", "status"], name="img_asset_owner_status_idx"),
                    models.Index(fields=["visibility", "status"], name="img_asset_visibility_idx"),
                ],
            },
        ),
    ]
